server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://192.168.200.109:5432/
    username: postgres
    password: stroller3jo
    driver-class-name: org.postgresql.Driver

logging:
  level:
    ROOT: info